<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\animation.gif" />
    <None Remove="Assets\Collectible\fish4.png" />
    <None Remove="Assets\FishImage.gif" />
    <None Remove="Assets\fishingrod.png" />
    <None Remove="Assets\Fishs\fish1.png" />
    <None Remove="Assets\Fish\fish4.png" />
    <None Remove="Assets\fish_hook.png" />
    <None Remove="Assets\Garbage\fish4.png" />
    <None Remove="Assets\Plus.png" />
    <None Remove="Assets\PlusReal.png" />
    <None Remove="Assets\RareFish\fish4.png" />
    <None Remove="Assets\water_splash.gif" />
  </ItemGroup>

  <ItemGroup>
      <Resource Include="Assets\**\*.png" CopyToOutputDirectory="Always" />
      <Resource Include="Assets\**\*.jpg" CopyToOutputDirectory="Always" />
      <Resource Include="Assets\**\*.jpeg" CopyToOutputDirectory="Always" />
      <Resource Include="Assets\**\*.gif" CopyToOutputDirectory="Always" />
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FishGenerator.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
